enum Routes {
  SPLASH = 'Splash',
  LOGIN = 'Login',
  REGISTER = 'Register',
  FORGOT = 'Forgot',
  HOME = 'Home',
  EXPLORE = 'Explore',
  CREATE_QUOTES = 'CreateQuotes',
  FAVORITES = 'Favorites',
  PROFILE = 'Profile',
  CATEGORIES = 'Categories',
  SUB_CATEGORIES = 'SubCategories',
  QUOTES = 'Quotes',
  SETTINGS = 'Settings',
  NOTIFICATIONS = 'Notifications',
  ABOUT = 'About',
  DOWNLOADS = 'Downloads',
  TEMPLATES = 'Templates',
  BOTTOM_TAB_NAVIGATOR = 'BottomTab',
  MAIN_NAVIGATOR = 'MainNavigator',
  ROUTES_NAVIGATOR = 'RoutesNavigators',
  DRAWER_NAVIGATOR = 'DrawerNavigator',
}

export default Routes;
